In [52]:
from typing import Optional, Tuple
import numpy as np

### Zadanie rozgrzewkowe:
Napisać mnożenie macierzy w ulubionym_\**_ języku programowania.

**Pytanko:** jakie muszą być wymiary mnożonych macierzy? (Który wymiar musi się "zgadzać"?)

**Zadanko:** Uzupełnić brakujące wymiary macierzy w docstringu (z dokładnością do ["alfa-konwersji"](https://pl.wikipedia.org/wiki/Konwersja_α))

In [53]:
def agh_superfast_matrix_multiply(a: np.matrix, b: np.matrix) -> np.matrix:
    """Perform totally ordinary multiplication of matrices.
    
    :param a: matrix with dimensions n by m
    :param b: matrix with dimensions m by p
    :return:  matrix with dimensions n by p
    """

    n = a.shape[0]
    m = a.shape[1]
    p = b.shape[1]
    c = np.zeros((n,p))
    
    for i in range(0,n):
        for j in range(0,p):
            for k in range(0,m):
                c[i, j] += a[i, k] * b[k, j]
    return c

m1 = np.matrix([[1, 2],
                [3, 4],
                [4, 5],
                [5, 1]])

m2 = np.matrix([[1, 2, 3],
                [4, 5, 6]])

res = agh_superfast_matrix_multiply(m1, m2)
assert np.allclose(res, m1 * m2), "Wrong multiplication result"

### Zadania
1. Przeczytać rozdz. 7. Kincaida i Cheney'a (Systems of Linear Equations).
2. Przeczytać rozdz. 8. Kincaida i Cheney'a (Additional Topics Concerning Systems of Linear Equations).
3. Napisać kod (w ulubionym_\**_ języku) do eliminacji Gaussa z i bez pivotingu.
4. Rozwiązać poniższy układ równań z pivotingiem i bez, porównać wyniki:

In [54]:
A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()

x = np.linalg.solve(A, b)

#### Algorytm Gaussa bez pivotingu

In [55]:
def naive_gauss(a, b):
    """Perform naive Gauss algorithm to solve system of linear equations
    
    :param a: matrix with dimensions n by n
    :param b: matrix with dimensions 1 by n
    :return:  matrix with dimensions 1 by n
    """
    n = a.shape[0]
    x = np.zeros(n)
    
    for k in range(0, n):
        for i in range(k + 1, n):
            xmult = a[i, k] / a[k, k]
            a[i, k] = xmult
            for j in range(k + 1, n):
                a[i, j] = a[i, j] - xmult * a[k, j]
            b[i] = b[i] - xmult * b[k]
    x[n - 1] = b[n - 1] / a[n - 1, n - 1]
    for i in range(n - 1, -1, -1):
        sum = b[i]
        for j in range(i + 1, n):
            sum = sum - a[i, j] * x[j]
        x[i] = sum / a[i, i]
    return np.matrix(x).transpose()

In [56]:
x_ngauss = np.linalg.solve(A, b)
display(x, x_ngauss)
assert np.allclose(x_ngauss, x), "Wrong multiplication result"

matrix([[ 0.21602477],
        [-0.00791511],
        [ 0.63524333],
        [ 0.74617428]])

matrix([[ 0.21602477],
        [-0.00791511],
        [ 0.63524333],
        [ 0.74617428]])

**Pytanie**: dlaczego wołamy `transpose()` na wektorze `b`?

Sprawdźmy, czy rozwiązanie jest ok (**Pytanie'**: dlaczego po prostu nie użyjemy `==` lub jakiegoś `equals`?):

#### Odpowiedź:
Bo do $A\cdot x=b$ potrzebujemy wektor kolumnowy $b$.
#### Odpowiedź':
Operujemy na liczbach zmienno przecinkowych, zatem przez niedokładność ich reprezentacji musimy porównywać je z pewną dokładnością. Pytamy zatem, czy są w pewnej odległości, zamiast czy są identyczne, bo bardzo prawdopowobne, że identyczne nie będą.

In [57]:
np.allclose(np.dot(A, x), b)

True

#### Algorytm Gaussa z pivotingiem

In [58]:
def pivot_gauss(a, b):
    """Perform pivot Gauss algorithm to solve system of linear equations
    :param a: matrix with dimensions n by n
    :param b: matrix with dimensions 1 by n
    :return:  matrix with dimensions 1 by n
    """
    n = a.shape[0]
    x = np.zeros(n)
    s = np.zeros(n)
    d = np.zeros(n, dtype = np.int)
    
    for i in range(0, n):
        d[i] = i
        smax = 0
        for j in range(0, n):
            smax = max(smax, abs(a[i, j]))
        s[i] = smax
        
    for k in range(0, n - 1):
        rmax = 0
        for i in range(k, n):
            r = abs(a[d[i], k] / s[d[i]])
            if r > rmax:
                rmax = r
                j = i
        tmp = d[j]
        d[j] = d[k]
        d[k] = tmp
        for i in range(k + 1, n):
            xmult = a[d[i], k] / a[d[k], k]
            a[d[i], k] = xmult
            for j in range(k + 1, n):
                a[d[i], j] = a[d[i], j] - xmult * a[d[k], j]
    
    for k in range(0, n):
        for i in range(k + 1, n):
            b[d[i]] = b[d[i]] - a[d[i], k] * b[d[k]]
    
    m = n-1
    x[m] = b[d[m]] / a[d[m], m]
    
    for i in range(n - 1, -1, -1):
        sum = b[d[i]]
        for j in range(i + 1, n):
            sum = sum - a[d[i], j] * x[j]
        x[i] = sum / a[d[i], i]
    return np.matrix(x).transpose()

### Zadania, c.d.

5. Zaimplementować algorytm faktoryzacji LU macierzy
6. (*) Zaimplementować funkcję sprawdzającą, czy dana macierz jest symetryczna i dodatnio określona
7. Zaimplementować algorytm faktoryzacji Cholesky'ego macierzy

#### Warunek na symetrię i dodatią określoność macierzy:
_"symetryczna macierz dodatnio określona $A$ ma rozkład Choleskiego, tzn. istnieje macierz odwracalna $L$, dla której $A = L L^T$ (symetria i dodatnia określoność – to warunki konieczne i dostateczne)"_ ~[Wikipedia](https://pl.wikipedia.org/wiki/Okre%C5%9Blono%C5%9B%C4%87_formy#Twierdzenia)

In [59]:
def agh_superfast_lu(a: np.matrix) -> Optional[Tuple[np.matrix, np.matrix]]:
    """Perform LU decomposition of a matrix.
    
    :param a: square matrix (n x n)
    :return:  tuple of (l, u) where:
        l is lower diagonal matrix of a
        u is upper diagonal matrix of a
        and a = l * u
    """
    
    n = a.shape[0]
    l = np.zeros((n, n))
    u = np.zeros((n, n))
    
    for k in range(0, n):
        l[k, k] = 1
        for j in range(k, n):
            sum = 0
            for s in range(0, k):
                sum += l[k, s] * u[s, j]
            u[k, j] = a[k, j] - sum
        for i in range(k + 1, n):
            sum = 0
            for s in range(0, k):
                sum += l[i, s] * u[s, k]
            l[i, k] = (a[i, k] - sum) / u[k, k]
    return (l, u)

def agh_superfast_check_spd(a: np.matrix) -> bool:
    """Check whether a matrix is symmetric and positive-definite (SPD).
    
    :param a: square matrix
    """
    l = agh_superfast_cholesky(a)
    llt = agh_superfast_matrix_multiply(l, l.transpose())
    return np.allclose(llt, a)

def agh_superfast_cholesky(a: np.matrix) -> Optional[np.matrix]:
    """Perform a Cholesky decomposition of a matrix.
    
    :param a: square matrix (SPD)
    :return:  matrix l that is lower diagonal matrix of a and a = l * l^t
    """
    
    n = a.shape[0]
    l = np.zeros((n, n))
    
    for k in range(0, n):
        sum = 0
        for s in range(0, k):
            sum += l[k, s] * l[k, s]
        l[k, k] = pow(a[k, k] - sum, 1 / 2)
        for i in range(k + 1, n):
            sum = 0
            for s in range(0, k):
                sum += l[i, s] * l[k, s]
            l[i, k] = (a[i, k] - sum) / l[k, k]
    return l

#### Działanie zaimplementowanych metod:

In [60]:
A = np.matrix([[5.0, 3.0, 2.0],
               [ 1.0, 2.0, 0.0],
               [ 3.0, 0.0, 4.0]])

LU = agh_superfast_lu(A)
print(LU[0], " = L")
print(LU[1], " = U")

[[ 1.          0.          0.        ]
 [ 0.2         1.          0.        ]
 [ 0.6        -1.28571429  1.        ]]  = L
[[ 5.          3.          2.        ]
 [ 0.          1.4        -0.4       ]
 [ 0.          0.          2.28571429]]  = U


In [61]:
A = np.matrix([[2.0, -1.0, 0.0],
               [-1.0, 2.0,-1.0],
               [ 0.0,-1.0, 2.0]])

L = agh_superfast_cholesky(A)
print(L, " = L")
print(L.transpose(), " = L^T")

[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]  = L
[[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]  = L^T


In [62]:
A = np.matrix([[2.0, -1.0, 0.0],
               [-1.0, 2.0,-1.0],
               [ 0.0,-1.0, 2.0]])

agh_superfast_check_spd(A)

True

### Zadania, opcjonalnie
5. zaimplementować metodę Jacobiego (iteracyjne rozwiązywanie układu równań liniowych)
6. za pomocą tejże metody rozwiązać powyższy układ równań

In [63]:
def jacobi(a, b):
    """Perform Jacobi iterative method to solve system of linear equations
    
    :param a: matrix with dimensions n by n
    :param b: matrix with dimensions 1 by n
    :return:  matrix with dimensions 1 by n
    """
    ITERATION_LIMIT = 1000
    n = a.shape[0]
    x = np.zeros_like(b)
    
    for it_count in range(ITERATION_LIMIT):
        x_new = np.zeros_like(x)

        for i in range(0, n):
            s1 = np.dot(a[i, :i], x[:i])
            s2 = np.dot(a[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / a[i, i]

        if np.allclose(x, x_new, atol=1e-10, rtol=0.0):
            break
            
        x = x_new
    return x

In [64]:
A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]])
b = np.array([6., 25., -11., 15.])

In [65]:
x = jacobi(A, b)
errors = np.dot(A, x) - b

print("Solution: ", x)
print("Error: ", errors)

Solution:  [ 1.  2. -1.  1.]
Error:  [ 3.95795396e-10 -7.29656335e-10  5.13315612e-10 -5.86034332e-10]


In [66]:
def jacobi_numpy(a, b):
    """Perform Jacobi iterative method using numpy functions
    
    :param a: matrix with dimensions n by n
    :param b: matrix with dimensions 1 by n
    :return:  matrix with dimensions 1 by n
    """
    # Initial x vector
    x = np.zeros(len(A[0]))
    
    # Number of iterations
    N = 30

    # Vector of the diagonal elements of A and subtract them from A
    D = np.diag(A)
    R = A - np.diagflat(D)

    # N iterations
    for i in range(N):
        x = (b - np.dot(R,x)) / D
    return x

In [67]:
x = jacobi_numpy(A, b)
errors = np.dot(A, x) - b

print("Solution: ", x)
print("Error: ", errors)

Solution:  [ 1.  2. -1.  1.]
Error:  [ 7.19939663e-11 -1.32647671e-10  9.33333411e-11 -1.06602727e-10]
